print("Hello World!")
input("Digite seu nome: ")
print("Hello World!")
input("Digite seu nome: ")
input("Digite seu nome: ")
print("Hello World!")
input("Digite seu nome: ")
print("Hello World!")
input("Digite seu nome: ")
print("Hello World!")
input("Digite seu nome: ")
